---
# tasks file for packer
- name: "packer | download zip file from remote src and unarchive it"
  unarchive:
    src: "{{ download_url}}"
    dest: /usr/local/bin
    remote_src: yes

- name: "packer | create symbolic link to bibnary containing patch as a W.A."
  file:
    src: "/usr/local/bin/pkg/packer_linux_amd64"
    dest: "/usr/local/bin/packer"
    state: link
